body:
  - type: textarea
    attributes:
      label: Request Description
      description: Describe what you'd like to see as a new enhancement.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternative Solutions
      description: Describe the alternatives you've considered.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Details
      description: Provide information that may be helpful.
